services:
  postgres:
    image: postgres:15
    restart: always
    user: postgres
    env_file:
      - .env # Load environment variables
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432" # Standard PostgreSQL port
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy # Ensures app starts only when DB is ready
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "9229:9229" # Debugging port
    volumes:
      - .:/app
      - /app/node_modules # Prevents overwriting container dependencies
    # command: [ "pnpm", "dev" ]
    command: [ "pnpm", "debug" ]

volumes:
  pgdata:
    name: pgdata # Ensures persistent PostgreSQL data storage
